<h1 align='center'> COMP2420/COMP6420 - Introduction to Data Management, Analysis and Security</h1>

<h2 align='center'> Lab 02 - Data Analysis with NumPy & Pandas</h2>

*****

In Lab 01, we studied the basic of data structures in Python. Clearly, visualizing the data in the form of tables instead of lists and dictionaries, would have been a much better experience for most of you. **NumPy** and **Pandas** modules in Python provide that ease of visualization and computation, especially while working with huge amounts of data.   

**Pandas** is one of the most widely used python modules for data science. It provides high-performance, easy to use structures and data analysis tools. Among other useful data structures, Pandas provides in-memory 2D table object called **Dataframe**. It works like a spreadsheet with column names and row labels. With dataframes,Pandas is capable of providing many additional functionalities like creating pivot tables, computing columns based on other columns and plotting graphs.

**NumPy** (which stands for ‘Numeric Python’) is a Python module which provides fast mathematical computation on arrays and matrices. It provides the essential multi-dimensional array-oriented computing functionalities designed for high-level mathematical functions and scientific computation. Since, arrays and matrices are an essential part of the Machine Learning ecosystem, NumPy along with Machine Learning modules like Scikit-learn, Pandas, Matplotlib, TensorFlow, etc. complete the Python Machine Learning Ecosystem.

For those of you, who still aren't impressed by the computation power and speed instilled by these two modules, let's do a little test to observe the difference in computation time between traditional Python and NumPy. Let's call this test **'Why NumPy?'**. 

In [1]:
# First things first! 
# We can't proceed without importing the necessary modules
import numpy as np
import pandas as pd
# Notice how we have used aliases for both these modules 
# so we won't have to type in their full names repeatedly 
import time
import math

In [2]:
# Now, let's compute the time taken for traditional Python v/s NumPy 
# to add elements of two lists with 10 million items each

def trad_version():
    t1 = time.time()
    X = range(10000000)
    Y = range(10000000)
    Z = [x+y for x,y in zip(X,Y)]
    return time.time() - t1

def numpy_version():
    t1 = time.time()
    X = np.arange(10000000)
    Y = np.arange(10000000)
    Z = X + Y
    return time.time() - t1

traditional_time = trad_version()
numpy_time = numpy_version()

print("Traditional Time = " + "%.4f" %(traditional_time) + " s.")
print("NumPy Time       = " + "%.4f" %(numpy_time) + " s.")
print("We can see that NumPy is approximately %d times faster than Traditional Python." 
      %(round(traditional_time / numpy_time)))

Traditional Time = 0.7920 s.
NumPy Time       = 0.0886 s.
We can see that NumPy is approximately 9 times faster than Traditional Python.


Besides this, there are some other advantages like - 

1. For machine learning operations, t is much easier to use NumPy’s **ndarray** (which provides a lot of convenient and optimized implementations of essential mathematical operations on vectors) over traditional **lists**.

2. NumPy arrays are capable of performing all basic operations such as addition, subtraction, element-wise product, **matrix dot product**, element-wise division and conditional operations.

3. Pandas **DataFrame** and **Series** objects are simple and intuitive to access, offering a variety of functionalities like creating **pivot tables**, grouping similar data, computing columns based on other columns and **plotting graphs**.


Now that we have established the superiority of NumPy and Pandas over traditional Python, let's introduce you to the contents of these modules. Many of the functions and data structures discussed here, will be used repeatedly in the coming labs and assignments. So, **keep your eyes peeled**!! 
<br/><br/>


<h3 align='center'>Pandas</h3>

**Pandas** have two different data structures that we can use for manipulating different types of data. Here we will see - 

* **Series** (1-D data structures) - It is a 1-dimensional labeled array capable of holding any datatype (integers, strings, floating point numbers etc.). The axis labels are collectively referred to as the **index**.


* **DataFrames** (2-D data structures) - It is a 2-dimensional labeled data structure with columns of potentially different types. You can think of it like a **spreadsheet** or **SQL table**, or a **dictionary of Series objects**. It is generally the most commonly used pandas object. Like Series, DataFrame accepts many different kinds of input datatypes.

### Series

In [3]:
# Making a series from a list (with indexes / row names)
# If you don't specify index, default index is 0, 1, 2, 3 ...
s = pd.Series([1,2,3,4,5],index=['a', 'b', 'c', 'd', 'e'] )
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [4]:
# Series from dictionary, where the keys are used as index, and the values as series values 
dict_s = {'a' : 0., 'b' : 1., 'c' : 2.}
pd.Series(dict_s)

a    0.0
b    1.0
c    2.0
dtype: float64

In [5]:
# Operations on series work more or less the same way as lists
# 1st element of the series
print("1st element of series:", s[0], "\n")

1st element of series: 1 



In [6]:
# Element with index 'd'
print ("Element with index 'd':", s['d'], "\n")

Element with index 'd': 4 



In [7]:
# Slicing the given series
print(s[3:5], "\n")

d    4
e    5
dtype: int64 



In [8]:
# Comparing each element with the median of the series
print("Median:", s.median())
for item in s:
    print(item, "is larger than median" if item >= s.median() else "is smaller than median")

Median: 3.0
1 is smaller than median
2 is smaller than median
3 is larger than median
4 is larger than median
5 is larger than median


In [9]:
# Print the elements that are greater than the median of series
print(s[s > s.median()])

d    4
e    5
dtype: int64


### DataFrame

In [10]:
# Making a dataframe from a dictionary of series
dict_s = {'one' : pd.Series([1, 'Harry', 8.7], index=['a', 'b', 'd']),
          'two' : pd.Series([9, 'Matt', 7.5, 6.1], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(dict_s)
df

one   two
a      1     9
b  Harry  Matt
c    NaN   7.5
d    8.7   6.1

Passing an **index** (row labels) and **columns** (column labels) along with your data is optional, but if you pass an index and / or columns, you are guaranteeing the index and / or columns of the resulting **DataFrame**. Thus, a **dict of Series** plus a specific index will discard all data not matching up to the passed index.

You can also load a CSV file / Excel worksheet into a Python dataframe, using the following method:

In [11]:
df_cars = pd.read_csv('cars.csv')
# head() displays the first 5 rows of the resultant dataframe
df_cars.head()

type   mpg  cyl   disp     hp    wt  speed
0  AMC Ambassador Brougham  13.0    8  360.0  175.0  3821   11.0
1       AMC Ambassador DPL  15.0    8  390.0  190.0  3850    8.5
2       AMC Ambassador SST  17.0    8  304.0  150.0  3672   11.5
3         AMC Concord DL 6  20.2    6  232.0   90.0  3265   18.2
4           AMC Concord DL  18.1    6  258.0  120.0  3410   15.1

Similarly, there are some other common methods to -

* **df.columns** - returns a list of names of the columns
* **df.values** - returns all values without index and column names in numpy array
* **df.info()** - returns info about the data and datatypes for every column
* **df.head()** - returns the top 5 (default) rows of the dataframe
* **df.tail()** - returns the bottom 5 rows of the dataframe

In [12]:
# You can slice the dataframe in the following ways -

# Accessing individual columns
# df_cars['type']
# df_cars.hp
df_cars[['type','disp']].head()

type   disp
0  AMC Ambassador Brougham  360.0
1       AMC Ambassador DPL  390.0
2       AMC Ambassador SST  304.0
3         AMC Concord DL 6  232.0
4           AMC Concord DL  258.0

In [13]:
# Accessing individual row
# df_cars.loc[2] 
df_cars.iloc[1:3]

type   mpg  cyl   disp     hp    wt  speed
1  AMC Ambassador DPL  15.0    8  390.0  190.0  3850    8.5
2  AMC Ambassador SST  17.0    8  304.0  150.0  3672   11.5

In [14]:
# Accessing particular columns of selected rows
# df_cars[['type','disp']][1:3]
df_cars[1:3][['type','cyl']]

type  cyl
1  AMC Ambassador DPL    8
2  AMC Ambassador SST    8

### Filtering Rows
We can also filter rows or select a subset of interesting rows based on the boolean comparison of two or more columns.

In [15]:
positive_pt = df_cars[df_cars.hp > df_cars.disp]
positive_pt

type   mpg  cyl  disp     hp    wt  speed
240        Maxda RX-3  18.0    3  70.0   90.0  2124   13.5
248  Mazda RX-2 Coupe  19.0    3  70.0   97.0  2330   13.5
249        Mazda RX-4  21.5    3  80.0  110.0  2720   13.5
250     Mazda RX-7 Gs  23.7    3  70.0  100.0  2420   12.5

Now, let's see how much you have grasped from the brief rundown above. Answer the following questions based on the above dataframe. It should be already loaded into memory if you've run the above cells, so, you don't have to load the dataframe from the CSV again.

## Exercise 1

1. How would you print the last 25 rows of the dataframe?

In [16]:
# YOUR ANSWER HERE

df_cars.tail(25)

type   mpg  cyl   disp     hp    wt  speed
381                Volkswagen Dasher  25.0    4   90.0   71.0  2223   16.5
382                Volkswagen Dasher  26.0    4   79.0   67.0  1963   15.5
383                Volkswagen Dasher  30.5    4   97.0   78.0  2190   14.1
384                 Volkswagen Jetta  33.0    4  105.0   74.0  2190   14.2
385             Volkswagen Model 111  27.0    4   97.0   60.0  1834   19.0
386                Volkswagen Pickup  44.0    4   97.0   52.0  2130   24.6
387     Volkswagen Rabbit C (Diesel)  44.3    4   90.0   48.0  2085   21.7
388  Volkswagen Rabbit Custom Diesel  43.1    4   90.0   48.0  1985   21.5
389         Volkswagen Rabbit Custom  29.0    4   97.0   78.0  1940   14.5
390         Volkswagen Rabbit Custom  31.9    4   89.0   71.0  1925   14.0
391              Volkswagen Rabbit L  36.0    4  105.0   74.0  1980   15.3
392                Volkswagen Rabbit  29.0    4   90.0   70.0  1937   14.0
393                Volkswagen Rabbit  29.0    4   90.0   70.0  1937   14.2
394                Volkswagen Rabbit  29.5    4   97.0   71.0  1825   12.2
395                Volkswagen Rabbit  41.5    4   98.0   76.0  2144   14.7
396              Volkswagen Scirocco  31.5    4   89.0   71.0  1990   14.9
397      Volkswagen Super Beetle 117   NaN    4   97.0   48.0  1978   20.0
398          Volkswagen Super Beetle  26.0    4   97.0   46.0  1950   21.0
399                Volkswagen Type 3  23.0    4   97.0   54.0  2254   23.5
400                      Volvo 144EA  19.0    4  121.0  112.0  2868   15.5
401               Volvo 145E (Wagon)  18.0    4  121.0  112.0  2933   14.5
402                      Volvo 244DL  22.0    4  121.0   98.0  2945   14.5
403                        Volvo 245  20.0    4  130.0  102.0  3150   15.7
404                      Volvo 264GL  17.0    6  163.0  125.0  3140   13.6
405                     Volvo Diesel  30.7    6  145.0   76.0  3160   19.6

2. How would you filter out the cars which have a mileage (mpg) greater than 40, but speed less than 20?  

In [17]:
# YOUR ANSWER HERE

df_cars[(df_cars['mpg'] > 40) & (df_cars['speed'] < 20)]

type   mpg  cyl  disp    hp    wt  speed
117            Datsun 210  40.8    4  85.0  65.0  2110   19.2
232   Honda Civic 1500 GL  44.6    4  91.0  67.0  1850   13.8
247             Mazda GLC  46.6    4  86.0  65.0  2110   17.9
340  Renault Lecar Deluxe  40.9    4  85.0   NaN  1835   17.3
395     Volkswagen Rabbit  41.5    4  98.0  76.0  2144   14.7

Suppose, your friend Matt wants to buy a new car, and asks for your help to zero in on the best suitable model for him from this dataset. Someone told him that mileage is a very important factor while choosing a car, and wants you to sort the dataset by decreasing value of mpg.   

3. How would you print the data for **top 15 cars** with the highest miles per gallon (mpg)?

In [18]:
# YOUR ANSWER HERE
# SAVE YOUR RESULT TO A NEW DATAFRAME FOR FURTHER COMPUTATIONS

df_mpg_dec = df_cars.sort_values(['mpg'], ascending=False).head(15)
df_mpg_dec

type   mpg  cyl   disp    hp    wt  speed
247                        Mazda GLC  46.6    4   86.0  65.0  2110   17.9
232              Honda Civic 1500 GL  44.6    4   91.0  67.0  1850   13.8
387     Volkswagen Rabbit C (Diesel)  44.3    4   90.0  48.0  2085   21.7
386                Volkswagen Pickup  44.0    4   97.0  52.0  2130   24.6
380       Volkswagen Dasher (Diesel)  43.4    4   90.0  48.0  2335   23.7
388  Volkswagen Rabbit Custom Diesel  43.1    4   90.0  48.0  1985   21.5
395                Volkswagen Rabbit  41.5    4   98.0  76.0  2144   14.7
340             Renault Lecar Deluxe  40.9    4   85.0   NaN  1835   17.3
117                       Datsun 210  40.8    4   85.0  65.0  2110   19.2
130                   Datsun B210 GX  39.4    4   85.0  70.0  2070   18.6
373                   Toyota Starlet  39.1    4   79.0  58.0  1755   16.9
290                   Plymouth Champ  39.0    4   86.0  64.0  1875   16.4
357            Toyota Corolla Tercel  38.1    4   89.0  60.0  1968   18.8
237                      Honda Civic  38.0    4   91.0  67.0  1965   15.0
303           Plymouth Horizon Miser  38.0    4  105.0  63.0  2125   14.7

He further finds out that a vehicle's horsepower when divided by its weight gives us the power-to-weight ratio, which is represented as horsepower to 10 pounds. **The higher that number, the better your car is going to be in terms of performance.** 

3. How would you find out the top 10 cars (from the above result) with the highest **horsepower (hp) / weight** ratio?

In [19]:
# YOUR ANSWER HERE
# WORK ON THE RESULTANT DATFRAME FROM PREVIOUS QUESTION 
# AND TRANSFER YOUR RESULTS TO A NEW DATAFRAME   

df_mpg_dec['hp/wt'] = df_mpg_dec['hp'] / df_mpg_dec['wt']
df_hpwt_dec = df_mpg_dec.sort_values(['hp/wt', 'mpg'], ascending=False).head(10)
df_hpwt_dec

type   mpg  cyl   disp    hp    wt  speed     hp/wt
232     Honda Civic 1500 GL  44.6    4   91.0  67.0  1850   13.8  0.036216
395       Volkswagen Rabbit  41.5    4   98.0  76.0  2144   14.7  0.035448
290          Plymouth Champ  39.0    4   86.0  64.0  1875   16.4  0.034133
237             Honda Civic  38.0    4   91.0  67.0  1965   15.0  0.034097
130          Datsun B210 GX  39.4    4   85.0  70.0  2070   18.6  0.033816
373          Toyota Starlet  39.1    4   79.0  58.0  1755   16.9  0.033048
247               Mazda GLC  46.6    4   86.0  65.0  2110   17.9  0.030806
117              Datsun 210  40.8    4   85.0  65.0  2110   19.2  0.030806
357   Toyota Corolla Tercel  38.1    4   89.0  60.0  1968   18.8  0.030488
303  Plymouth Horizon Miser  38.0    4  105.0  63.0  2125   14.7  0.029647

Lastly, Matt finds out that Canberra city only has authorized service centers for **Honda** and **Toyota**. If he buys any other car makes, he would have to go to Sydney for servicing and parts.

4. How would you filter only the cars produced by Honda and Toyota from the above result?

In [20]:
# YOUR ANSWER HERE
# WORK ON THE RESULTANT DATFRAME FROM PREVIOUS QUESTION 
# AND TRANSFER YOUR RESULTS TO A NEW DATAFRAME  

df_hpwt_dec[df_hpwt_dec['type'].str.contains("Honda") | df_hpwt_dec['type'].str.contains("Toyota")]

type   mpg  cyl  disp    hp    wt  speed     hp/wt
232    Honda Civic 1500 GL  44.6    4  91.0  67.0  1850   13.8  0.036216
237            Honda Civic  38.0    4  91.0  67.0  1965   15.0  0.034097
373         Toyota Starlet  39.1    4  79.0  58.0  1755   16.9  0.033048
357  Toyota Corolla Tercel  38.1    4  89.0  60.0  1968   18.8  0.030488

If all went well, you would have provided your friend with a choice between **4 cars**, which is a pretty good shortlist, considering you started with **406 cars** in your original dataset. **GOOD JOB!**

<h3 align='center'>NumPy</h3>

**NumPy** is a core Python module for scientific computation. It provides a high-performance multidimensional array object, and tools for working with these arrays.


### Arrays

A NumPy **Array** is a grid of values, all of the same type, and is indexed by a tuple of non-negative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension. We can initialize numpy arrays from nested Python lists, and access elements using square brackets.

In [21]:
# 1-dimensional arrays
x = np.array([2,5,18,14,4])
print ("\n Deterministic 1-dimensional array \n")
print (x)
print ("Shape:", x.shape)


 Deterministic 1-dimensional array 

[ 2  5 18 14  4]
Shape: (5,)


In [22]:
# 2-dimensional arrays
x = np.array([[2,5,18,14,4], [12,15,1,2,8]])
print ("\n Deterministic 2-dimensional array \n")
print (x)
print ("Shape:", x.shape)

# 2-dimensional random generated array
x = np.random.rand(5,5)
print ("\n Random 5x5 2-dimensional array \n")
print (x)
print ("Shape:", x.shape)


 Deterministic 2-dimensional array 

[[ 2  5 18 14  4]
 [12 15  1  2  8]]
Shape: (2, 5)

 Random 5x5 2-dimensional array 

[[0.39660612 0.33138528 0.72720514 0.62376863 0.46662678]
 [0.32902901 0.77541495 0.84226661 0.62345342 0.79727929]
 [0.51099606 0.98147556 0.87095593 0.09356212 0.94416612]
 [0.76647735 0.27546294 0.37888484 0.3446502  0.109916  ]
 [0.05640773 0.3017037  0.01810456 0.32560436 0.94938673]]
Shape: (5, 5)


In [23]:
# 4x4 array of zeroes
x = np.zeros((4,4))
print ("\n 4x4 array with zeros \n")
print(x)
print ("Shape:", x.shape)


 4x4 array with zeros 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (4, 4)


In [24]:
# 4x4 array of ones
x = np.ones((4,4))
print ("\n 4x4 array with ones \n")
print (x)
print ("Shape:", x.shape)


 4x4 array with ones 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Shape: (4, 4)


In [25]:
# identity matrix of size 4
x = np.eye(4)
print ("\n Identity matrix of size 4\n")
print(x)
print ("Shape:", x.shape)


 Identity matrix of size 4

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Shape: (4, 4)


### Manipulating Arrays

In [26]:
x = np.random.rand(4,3)
print(x)
print("\n Row zero \n")
print(x[0])
print("\n Column 2 \n")
print(x[:,2])
print("\n Submatrix \n")
print(x[1:3,0:2])
print("\n Entries > 0.5 \n")
print(x[x>0.5])
print("\n Single Element\n")
print(x[1,2])

[[0.69907911 0.12260673 0.90198401]
 [0.42278609 0.22161711 0.62806526]
 [0.87872716 0.46361163 0.9660629 ]
 [0.14058471 0.91941752 0.16176263]]

 Row zero 

[0.69907911 0.12260673 0.90198401]

 Column 2 

[0.90198401 0.62806526 0.9660629  0.16176263]

 Submatrix 

[[0.42278609 0.22161711]
 [0.87872716 0.46361163]]

 Entries > 0.5 

[0.69907911 0.90198401 0.62806526 0.87872716 0.9660629  0.91941752]

 Single Element

0.6280652563533042


### Array Arithmetic

In [27]:
x = np.random.rand(2,4)
print (x)
print('\n Mean value of all elements')
print (np.mean(x))

print('\n Standard Deviation of all elements')
print (np.std(x)) 

print('\n Median value of all elements')
print (np.median(x)) 

print('\n Sum of all elements')
print (np.sum(x)) 

print('\n Product of all elements')
print (np.prod(x)) 

print ("\n Transpose of the matrix \n")
print (x.T)
print ("Shape:", x.T.shape)

# Multiplication and addition with scalar value
print("\n Matrix 2x+1 \n") 
print(2*x + 1)

y = np.array([2,-1,3])
z = np.array([-1,2,2])
# Vector-Vector Dot Product
print('\n y:',y)
print(' z:',z)
print('\n Vector-Vector Dot Product')
print(np.dot(y,z))

[[0.40327352 0.34883077 0.40083567 0.77247663]
 [0.60533681 0.28006746 0.16177201 0.02215552]]

 Mean value of all elements
0.37434354761475414

 Standard Deviation of all elements
0.22140702243606195

 Median value of all elements
0.3748332209708496

 Sum of all elements
2.994748380918033

 Product of all elements
2.646739972266372e-05

 Transpose of the matrix 

[[0.40327352 0.60533681]
 [0.34883077 0.28006746]
 [0.40083567 0.16177201]
 [0.77247663 0.02215552]]
Shape: (4, 2)

 Matrix 2x+1 

[[1.80654703 1.69766155 1.80167133 2.54495325]
 [2.21067361 1.56013492 1.32354402 1.04431104]]

 y: [ 2 -1  3]
 z: [-1  2  2]

 Vector-Vector Dot Product
2


## Exercise 2

We have borrowed the following example from [Philipp Janert](http://shop.oreilly.com/product/9780596802363.do)’s book. In this example we will use the famous Iris Flower dataset.

We will do some Machine Learning (ML) without explicitly using any fancy ML techniques. We have two different sets of data with us for this dataset

* [Train Data](./iris_train.csv), and 
* [Test Data](./iris_test.csv)

You should download both files and save it under a directory named ‘data’ in your current working directory. 

Iris data has five columns, namely - 
* sepal_length 
* sepal_width 
* pedal_length 
* pedal_width 
* class

Description of each field can be found [here](https://archive.ics.uci.edu/ml/datasets/iris).

Our dumb ML algorithm is known as **Nearest Neighbour Approach**, where we will predict the class label for a point in test set to be equal to class label of the nearest point in train set.

**HINT 1**: _For 2.1, 2.2, 2.3, 2.4, it would be worth looking at examples in class on how to read numpy arrays from csv files._

**HINT 2**: _Consider using np.argmin for task 5. You can also have a look at the class example to see how we got distance of a point from all other points._

1. Read the train set data into a numpy array (you can call it **train_features**) to get the train features. Use columns 0,1,2,3 from the csv.

In [28]:
# YOUR ANSWER HERE


2. Read the train set labels into a numpy array (you can call it **train_labels**) to get the training labels/classes. Use only column 4 for this array.

In [29]:
# YOUR ANSWER HERE

# Print unique labels


3. Similarly, read the test set data into a numpy array(you  can call it **test_features**) to get test features, using columns 0,1,2,3 from the iris_test.csv. Also, read the test set labels into a numpy array(and call it **test_labels**) to get test labels/classes, using only column 4.

In [30]:
# YOUR ANSWER HERE


4. Write code for the following -
    * For each point in the test set, find the closest point in the train set.
    
    * The test instance gets the label of the closest point, save it as predicted_label.

In [31]:
# YOUR ANSWER HERE

# Going through each point in dataset

    # Calculating difference between a point in test set 
    # to all points in train set
    
    # Finding the location of the nearest point in train set
    

5. Now find the accuracy of our predictions by comparing the value of **predicted_label** with **test_label** for each value in the **test_labels**. 

In [32]:
# YOUR ANSWER HERE
